language: ruby
rvm:
  - 2.4.1
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake
